version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  modules-download-mode: readonly
  allow-parallel-runners: true
  tests: true
  go: "1.25"

linters:
  default: standard
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - gocognit
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unparam
    - unused
  disable:
    - depguard
    - exhaustruct
  settings:
    gocognit:
      min-complexity: 22
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G404
    nolintlint:
      require-explanation: true
      require-specific: true
    revive:
      severity: warning
      rules:
        - name: exported
          severity: warning
        - name: indent-error-flow
        - name: redefines-builtin-id

formatters:
  enable:
    - gofmt
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  fix: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - linters:
        - errcheck
      text: "Error return value is not checked"

severity:
  default: error
  rules:
    - linters:
        - gocognit
        - gocyclo
      severity: warning
